export const data = [
    {
        id: 1,
        title: "Куртка",
        desc: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        price: "52.00",
        img: "../img/block1.png",
        gender: "man",
        size: "M",
    },
    {
        id: 2,
        title: "Костюм",
        desc: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        price: "49.00",
        img: "../img/block2.png",
        gender: "woman",
        size: "S",
    },
    {
        id: 3,
        title: "Свитшот",
        desc: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        price: "26.35",
        img: "../img/block3.png",
        gender: "man",
        size: "L",
    },
    {
        id: 4,
        title: "Майка",
        desc: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        price: "7.99",
        img: "../img/block4.png",
        gender: "man",
        size: "M",
    },
    {
        id: 5,
        title: "Пиджак",
        desc: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        price: "39.00",
        img: "../img/block5.png",
        gender: "woman",
        size: "XS",
    },
    {
        id: 6,
        title: "Блузка",
        desc: "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        price: "12.39",
        img: "../img/block6.png",
        gender: "woman",
        size: "S",
    },
];
